// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Data.SqlServer;

namespace ToDoApp.Data.SqlServer.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    [Migration("20190822112437_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoApp.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("ToDoApp.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ToDoItemId");

                    b.HasKey("Id");

                    b.HasIndex("ToDoItemId");

                    b.ToTable("TaskItem");
                });

            modelBuilder.Entity("ToDoApp.Domain.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ToDoItem");
                });

            modelBuilder.Entity("ToDoApp.Domain.TaskItem", b =>
                {
                    b.HasOne("ToDoApp.Domain.ToDoItem")
                        .WithMany("TaskItems")
                        .HasForeignKey("ToDoItemId");
                });

            modelBuilder.Entity("ToDoApp.Domain.ToDoItem", b =>
                {
                    b.HasOne("ToDoApp.Domain.Project")
                        .WithMany("ToDoItems")
                        .HasForeignKey("ProjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
